### ISSUE TITLE
spelling error

### ISSUE THREAD

**Issue by lettergram** [rlister/slackbotsy#11]
It appears as though there is a spelling error

```
/Library/Ruby/Gems/2.0.0/gems/slackbotsy-0.4.2/lib/slackbotsy/bot.rb:28:in `parse_outgoing_tokens': undefined method `to_set' for nil:NilClass (NoMethodError)
from /Library/Ruby/Gems/2.0.0/gems/slackbotsy-0.4.2/lib/slackbotsy/bot.rb:15:in `initialize'
from chat.rb:11:in `new'
from chat.rb:11:in `<main>'
```

Just need to change:

```
/slackbotsy/bot.rb:28
------
end.to_set
```

**Comment by rlister** [comment]
Fixed by https://github.com/rlister/slackbotsy/commit/72a692e686e2f565cc7fbaa658fec7b12c23a6e8

Now handles a `nil` outgoing token correctly.
